stages:
  - build-image

build_postgres_image:
  stage: build-image
  image: docker:24.0.7 
  services:
    - docker:24.0.7-dind 
  variables:
    IMAGE_TAG: "$CI_REGISTRY_IMAGE/postgres-db:latest"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "กำลัง Build Image..."
    - docker build -t $IMAGE_TAG -f postgres/dockerfile/Dockerfile.postgres ./postgres
    - echo "กำลัง Push Image ขึ้น GitLab Registry..."
    - docker push $IMAGE_TAG
  only:
    - main