version: '3.8'

services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey_cache
    network_mode: "host"
    volumes:
      - redisvalkey:/data
    command: >
      valkey-server 
      --port 6379 
      --protected-mode yes 
      --user default off 
      --user imddce_admin on >g0Uc;;myogs96dkiIN ~* +@all
    restart: always

volumes:
  redisvalkey:        
    driver: local