version: '3.8'

services:
  garage:
    image: dxflrs/garage:v2.2.0
    container_name: garage
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./garage.toml:/etc/garage.toml
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data

  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    environment:
      API_BASE_URL: "http://127.0.0.1:3903"
      S3_ENDPOINT_URL: "http://127.0.0.1:3900"
      HTTP_BASIC_AUTH_USER: "imddce"                
      HTTP_BASIC_AUTH_PASSWORD: "g0Uc;;myogs96dkiIN" 
    depends_on:
      - garage

volumes:
  garage_meta:
    driver: local
  garage_data:
    driver: local